Feature/service development
SoftLion-Co/prototype-fr pull request #86
Opened 2023-08-01 12:23 UTC by Bakuzov

2023-08-01 16:38 UTC, yuro4kaw requested changes
-Використати тег section для секції

-Файли цієї секції створені не в потрібній папці, правильна папка для створення файлів сторінки service: component/service
-Стилі не повинні бути в ServiceCardsComponent.module.scss цей модульний файл відноситься до іншого компонента.
-Лишні інклюди в ServiceCardsComponent.module.scss (Ще раз нагадую: перенести стилі з цього файлу)

-Форматування коду prettier DevelopmentSection.module.scss, ServiceCardsComponent.module.scss та перевірити інші файли
-Картинка (Навіщо вона була замінена?)

2023-08-02 10:38 UTC, Bakuzov commented
Використати тег section для секції

-Файли цієї секції створені не в потрібній папці, правильна папка для створення файлів сторінки service: component/service  - **пепемістив**
-Стилі не повинні бути в ServiceCardsComponent.module.scss цей модульний файл відноситься до іншого компонента.
  - **видалив, вони там зайві помилко туди розмістив**
-Лишні інклюди в ServiceCardsComponent.module.scss (Ще раз нагадую: перенести стилі з цього файлу)
**-все видалив**

-Форматування коду prettier DevelopmentSection.module.scss, ServiceCardsComponent.module.scss та перевірити інші файли.  **відформатував**
-Картинка (Навіщо вона була замінена?) 
-**зрозумів що моно було не змінювати картинку, оскільки вже зробив  - не став видаляти**

**Ще відформатував попередні секціі: Header, CustomAppsSection**

2023-08-02 13:18 UTC, yuro4kaw requested changes
-Тег section використовуєм тільки на секції, на компонентах карточок мають бути div
-Навіщо ще одна картинка "analytics-and-planning+"?
-Переробити марджини від заголовку вниз: 80рх, 60рх, 40рх, 40рх (Притримуємось одинакового стандарту)
-Переробити в секції CustomApps margin від заголовку вниз а не від карточок вверх (Притримуємось одинакового стандарту)
-Переробити interface DevelopmentCardComponent.tsx на валідний TypeScript. Навіщо прописувати "variant1", "variant2" якщо всеодно компонент приймає string як третій варіант. Аналогічно і з undefined, навіщо він там якщо у нас в інтерфейсі ствоїть символ "?" що означає що значення може і не надходити.
-Невідповідність макету ширина списку ul на mobile, tablet, laptop, desktop версії. З макету взята ширина тільки текстового блоку, без синьої картинки-індикатора, і на проекті ці ширина застосовується вже для всього li елемента разом із індикатором. Порівняй ще раз ширину ul на макеті і в себе.
-Видалення непотрібних інклюдів  в файлі components/service/DevelopmentCardMobileComponent.module.scss
-Стягнути зміни з гілки test і використати картинку синьої крапки для li списку за адресою: images/project/request-list.svg. свою картинку видалити

2023-08-02 19:07 UTC, Bakuzov commented
Крім останньої правки.
Картинка не затягнулась. Бо тест не затягнувся, конфлікти виникають

2023-08-03 15:41 UTC, yuro4kaw requested changes
-Тег section на секції DevelopmentSection
-Видалити непотрібне фото point.svg
-Видалити правки по package-lock.json (Перед наступними комітами просто видаляємо зміни з цього файлу)
-Відступ у секції CustomApps від заголовку до карточок не по стандарту: 80рх 60рх 40рх 40рх.

2023-08-04 11:19 UTC, Bakuzov commented
![Screenshot_1](https://github.com/SoftLion-Co/prototype-fr/assets/100297704/496d5501-990e-4796-a922-6e0fd2dd7119)
![Screenshot_7](https://github.com/SoftLion-Co/prototype-fr/assets/100297704/bda8d613-d37a-441c-99bc-f40bd8a00dee)

2023-08-05 10:16 UTC, merged